### ISSUE TITLE
不匹配

### ISSUE THREAD

**Issue by 3341232786** [LazyAlienServer/Where2go#10]
每次重新载入插件后提示
[where2go]: 读取配置文件失败，使用默认值: Mismatched input type: expected class <class 'str'> but found data with class <class 'list'>

可以将config.py里的内容改为

from mcdreforged.api.all import Serializable

class COMMAND_CONFIG(Serializable):
    waypoints: str = "!!wp"
    whereis: str = "!!vris"
    here: str = "!!here"
    fastsearch_regex: str = "^(\w+)在哪？?"
    fastsearch_prompt: str = "XXX在哪"

class PLAYER_API_CONFIG(Serializable):
    prefix_regex: str = "(?:\[.+\])?" 
    player_pos_command: str = "data get entity {player} Pos"
    player_dimension_command: str = "data get entity {player} Dimension"
    player_pos_regex: str = "^{prefix_regex}(\w+) has the following entity data: \[(-?[0-9.]+)d, (-?[0-9.]+)d, (-?[0-9.]+)d\]"
    player_dimension_regex: str = '^{prefix_regex}(\w+) has the following entity data: "minecraft:(\w+)"'
    player_notfound_regex: str = '^No entity was found'
    player_list_command: str = "list"
    player_list_sep: str = ", "
    player_list_regex: str = '^There are [0-9]+ of a max of [0-9]+ players online: (.+)*'
    highlight_command: str = "effect give {player} minecraft:glowing 15 0 true"

class CONFIG(Serializable):
    command: COMMAND_CONFIG = COMMAND_CONFIG()
    player_api: PLAYER_API_CONFIG = PLAYER_API_CONFIG()

**Comment by tanhHeng** [comment]
请提供插件版本、重载后的配置文件和MCDR版本，以帮助我们在其他环境下复现此问题并debug

**Comment by 3341232786** [comment]
原版本是Where2go-v0.2.2
我修改了部分内容
[[路径点]Where2go-v0.2.2.zip](https://github.com/user-attachments/files/16825035/Where2go-v0.2.2.zip)

**Comment by 3341232786** [comment]
已经产生配置文件后重新载入显示
[MCDR] [22:38:29] [TaskExecutor/INFO] [where2go]: 配置文件已加载
[MCDR] [22:38:29] [TaskExecutor/INFO] [where2go]: 读取配置文件失败，使用默认值: Mismatched input type: expected class <class 'str'> but found data with class <class 'list'>
![image](https://github.com/user-attachments/assets/1cc76fe4-aa3c-4b93-a7b6-5237d26bbc32)

**Comment by 3341232786** [comment]
[Server] [22:39:55] [Server thread/INFO]: <Neferula> !!wp list
[Server] [22:40:05] [Server thread/INFO]: <Neferula> !!here
Exception in thread where2go-player_pos:
Traceback (most recent call last):
  File "C:\Users\a\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\a\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "G:\WwwServer1.20.1v2\Server\Survival\mcdreforged\api\decorator\new_thread.py", line 29, in wrapped_target
    raise e from None
  File "G:\WwwServer1.20.1v2\Server\Survival\mcdreforged\api\decorator\new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\Where2go-v0.2.2.mcdr\where2go\__init__.py", line 139, in player_pos
  File "plugins\Where2go-v0.2.2.mcdr\where2go\utils\api\__init__.py", line 51, in get_player_list
  File "G:\WwwServer1.20.1v2\Server\Survival\mcdreforged\plugin\server_interface.py", line 449, in execute
    self._mcdr_server.send(text, encoding=encoding)
  File "G:\WwwServer1.20.1v2\Server\Survival\mcdreforged\mcdr_server.py", line 498, in send
    raise TypeError()
TypeError
[Server] [22:40:11] [Server thread/INFO]: <Neferula> !!vris Neferula
Exception in thread where2go-player_pos:
Traceback (most recent call last):
  File "C:\Users\a\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\a\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "G:\WwwServer1.20.1v2\Server\Survival\mcdreforged\api\decorator\new_thread.py", line 29, in wrapped_target
    raise e from None
  File "G:\WwwServer1.20.1v2\Server\Survival\mcdreforged\api\decorator\new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\Where2go-v0.2.2.mcdr\where2go\__init__.py", line 141, in player_pos
TypeError: argument of type 'NoneType' is not iterable
>

**Comment by 3341232786** [comment]
list正常

[Server] [22:41:34] [Server thread/INFO]: <Neferula> xaero-waypoint:可乐:可:695:71:570:9:false:0:Internal-overworld-waypoints
[Server] [22:41:35] [Server thread/INFO]: <Neferula> !!wp add xaero-waypoint:可乐:可:695:71:570:9:false:0:Internal-overworld-waypoints
[Server] [22:41:41] [Server thread/INFO]: <Neferula> !!wp list
![image](https://github.com/user-attachments/assets/4b0d749a-02a5-4263-adf0-4073d26fe02f)

**Comment by tanhHeng** [comment]
已在`v0.2.3`尝试修复
